FROM nginx

# Copy base nginx server configuration
COPY ./server/nginx.conf /etc/nginx/
COPY ./server/api_json_errors.conf /etc/nginx/

# COPY ./etc/nginx/api_gateway.conf /etc/nginx/
# COPY ./etc/nginx/api_conf.d/ /etc/nginx/api_conf.d/

# COPY ./cdp-dev-nginx/default.conf /etc/nginx/conf.d/default.conf
